language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

sudo: false

env:
  - TESTBENCH_VERSION="~3.0.0"
  - TESTBENCH_VERSION="~3.1.0"

before_install:
  - sed -i s/~3.0.0\|\|~3.1.0/${TESTBENCH_VERSION}/ composer.json
  - composer update # Use update since we'll be changing the composer.json

script: vendor/bin/phpunit tests
